<SplashScreen>
    name:"splash"
    MDFloatLayout:
        md_bg_color: 0/255, 108/255, 133/255, 1
        Image:
            source: "images/LOGO.png"
            allow_stretch: 0.9, 0.9
            pos_hint:{'center_x': 0.5}
        MDLabel:
            pos_hint:{'center_x': 0.5, 'center_y':0.3}
            halign: 'center'
            theme_text_color: 'Custom'
            text_color: 1,1,1,1
            font_size: "35sp"
            font_name: "Fonts/Poppins-Semibold.ttf"